In [2]:
#导包
import numpy as np
import pandas as pd
import os
os.chdir('D:\Git\Git\pandasProject')
os.getcwd()

'D:\\Git\\Git\\pandasProject'

In [1]:
# 1.加载数据
house_df = pd.read_csv('./Data/house_data.csv')
house_df

NameError: name 'pd' is not defined

- 准备动作 -> 查看数据集

In [4]:
# 1. 查看数据前5行
house_df.head()

# 2. 查看列数据分布
house_df.info()

# 3. 查看列统计指标
house_df.describe()
house_df.describe(include='all')

# 4. 查查数据形状
house_df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2760 entries, 0 to 2759
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   district     2760 non-null   object
 1   address      2760 non-null   object
 2   title        2760 non-null   object
 3   house_type   2760 non-null   object
 4   area         2760 non-null   float64
 5   price        2760 non-null   float64
 6   floor        2760 non-null   object
 7   build_time   2760 non-null   object
 8   district_id  2760 non-null   int64
 9   update_time  2760 non-null   object
 10  view_num     2760 non-null   int64
 11  extra_info   2760 non-null   object
 12  link         2760 non-null   object
dtypes: float64(2), int64(2), object(9)
memory usage: 280.4+ KB

(2760, 13)

- 完成具体需求

In [5]:
# 1. 找到租金最低，和租金最高的房子
# 思路1：排序
house_df.sort_values('price').head(1) # 价格最低
house_df.sort_values('price').tail(1) # 价格最高
# 思路2：筛选
house_df[house_df['price'] == house_df['price'].min()]
house_df[house_df['price'] == house_df['price'].max()]

,district,address,title,house_type,area,price,floor,build_time,district_id,update_time,view_num,extra_info,link
1830,丰台区,丰台区40号院5号楼5单元75室,一室一厅 丰台区优质房源,四室两厅,186.6,1499.4,19层/共15层,1997年,1003,2025-03-31 21:48:37,2197,南北通透,https://example.com/house/11830

In [7]:
# 2.找到最近新上的10套房源
house_df.sort_values('update_time',ascending=False).head(10)

,district,address,title,house_type,area,price,floor,build_time,district_id,update_time,view_num,extra_info,link
1525,西城区,西城区93号院3号楼4单元15室,四室两厅 西城区优质房源,三室两厅,68.8,201.58,26层/共14层,2009年,1004,2026-03-10 21:48:37,3429,精装修,https://example.com/house/11525
1181,丰台区,丰台区67号院28号楼6单元90室,两室一厅 丰台区优质房源,两室两厅,65.2,1284.96,24层/共30层,2006年,1003,2026-03-10 21:48:37,2111,近地铁,https://example.com/house/11181
2022,顺义区,顺义区15号院3号楼11单元88室,一室一厅 顺义区优质房源,三室两厅,171.2,1456.00,10层/共10层,2018年,1007,2026-03-10 21:48:37,1530,南北通透,https://example.com/house/12022
1770,顺义区,顺义区91号院28号楼2单元9室,三室一厅 顺义区优质房源,四室两厅,60.1,801.87,9层/共33层,2007年,1007,2026-03-10 21:48:37,838,精装修,https://example.com/house/11770
1441,西城区,西城区5号院11号楼1单元63室,一室一厅 西城区优质房源,两室两厅,152.3,620.88,19层/共27层,2003年,1004,2026-03-10 21:48:37,3538,带车位,https://example.com/house/11441
2568,海淀区,海淀区55号院28号楼14单元69室,三室两厅 海淀区优质房源,两室两厅,121.6,396.67,28层/共14层,2004年,1002,2026-03-10 21:48:37,2817,近地铁,https://example.com/house/12568
267,顺义区,顺义区44号院16号楼14单元53室,三室一厅 顺义区优质房源,两室两厅,151.2,724.14,21层/共12层,2005年,1007,2026-03-09 21:48:37,3665,近地铁,https://example.com/house/10267
762,顺义区,顺义区99号院28号楼16单元57室,两室两厅 顺义区优质房源,两室两厅,93.6,651.13,28层/共16层,2004年,1007,2026-03-09 21:48:37,2678,电梯房,https://example.com/house/10762
1772,西城区,西城区69号院16号楼5单元58室,一室一厅 西城区优质房源,三室两厅,161.2,533.68,32层/共30层,2000年,1004,2026-03-09 21:48:37,34,南北通透,https://example.com/house/11772
931,海淀区,海淀区86号院6号楼5单元23室,三室两厅 海淀区优质房源,三室一厅,148.3,1171.22,2层/共26层,2002年,1002,2026-03-09 21:48:37,1675,电梯房,https://example.com/house/10931

In [12]:
# 3.查看所有更新时间
house_df.update_time.unique()

array(['2025-12-02 21:48:37', '2025-05-16 21:48:37',
       '2026-02-12 21:48:37', '2026-02-09 21:48:37',
       '2025-07-10 21:48:37', '2025-04-11 21:48:37',
       '2025-05-24 21:48:37', '2025-05-25 21:48:37',
       '2025-03-19 21:48:37', '2025-06-10 21:48:37',
       '2025-05-21 21:48:37', '2026-01-02 21:48:37',
       '2025-07-12 21:48:37', '2026-02-10 21:48:37',
       '2025-10-13 21:48:37', '2025-07-08 21:48:37',
       '2025-10-27 21:48:37', '2026-02-20 21:48:37',
       '2025-12-25 21:48:37', '2025-08-02 21:48:37',
       '2025-06-09 21:48:37', '2025-10-11 21:48:37',
       '2025-12-14 21:48:37', '2025-08-18 21:48:37',
       '2025-09-07 21:48:37', '2025-03-20 21:48:37',
       '2025-03-12 21:48:37', '2026-02-22 21:48:37',
       '2025-07-13 21:48:37', '2025-03-29 21:48:37',
       '2025-04-09 21:48:37', '2026-02-05 21:48:37',
       '2025-10-19 21:48:37', '2026-01-07 21:48:37',
       '2025-05-11 21:48:37', '2025-08-07 21:48:37',
       '2025-05-31 21:48:37', '2025-09-09 21:48:37',
       '2025-06-16 21:48:37', '2025-06-25 21:48:37',
       '2025-08-16 21:48:37', '2025-04-08 21:48:37',
       '2025-07-26 21:48:37', '2025-09-15 21:48:37',
       '2025-12-16 21:48:37', '2025-06-02 21:48:37',
       '2025-10-10 21:48:37', '2026-01-12 21:48:37',
       '2025-04-15 21:48:37', '2025-11-18 21:48:37',
       '2025-10-08 21:48:37', '2025-06-20 21:48:37',
       '2025-10-28 21:48:37', '2025-08-13 21:48:37',
       '2026-02-25 21:48:37', '2025-05-15 21:48:37',
       '2025-06-29 21:48:37', '2025-12-03 21:48:37',
       '2025-08-22 21:48:37', '2026-02-21 21:48:37',
       '2026-03-01 21:48:37', '2026-03-04 21:48:37',
       '2025-06-07 21:48:37', '2026-02-08 21:48:37',
       '2025-09-08 21:48:37', '2026-01-13 21:48:37',
       '2026-02-03 21:48:37', '2025-07-31 21:48:37',
       '2025-09-27 21:48:37', '2025-06-17 21:48:37',
       '2026-03-07 21:48:37', '2025-03-26 21:48:37',
       '2025-11-01 21:48:37', '2025-03-27 21:48:37',
       '2025-10-05 21:48:37', '2025-08-03 21:48:37',
       '2025-08-19 21:48:37', '2025-10-14 21:48:37',
       '2025-04-20 21:48:37', '2025-07-22 21:48:37',
       '2025-04-03 21:48:37', '2025-04-24 21:48:37',
       '2025-11-12 21:48:37', '2025-12-17 21:48:37',
       '2026-01-28 21:48:37', '2025-08-20 21:48:37',
       '2026-03-09 21:48:37', '2025-03-24 21:48:37',
       '2026-01-22 21:48:37', '2026-01-05 21:48:37',
       '2025-10-24 21:48:37', '2025-09-11 21:48:37',
       '2025-08-25 21:48:37', '2025-11-11 21:48:37',
       '2025-04-01 21:48:37', '2025-11-19 21:48:37',
       '2025-12-26 21:48:37', '2025-10-21 21:48:37',
       '2025-12-31 21:48:37', '2026-01-29 21:48:37',
       '2025-07-01 21:48:37', '2026-02-07 21:48:37',
       '2025-11-13 21:48:37', '2025-07-15 21:48:37',
       '2025-11-08 21:48:37', '2025-06-12 21:48:37',
       '2025-04-22 21:48:37', '2025-07-18 21:48:37',
       '2025-11-26 21:48:37', '2025-06-22 21:48:37',
       '2025-03-17 21:48:37', '2025-05-07 21:48:37',
       '2025-03-31 21:48:37', '2026-01-27 21:48:37',
       '2025-10-20 21:48:37', '2025-04-02 21:48:37',
       '2025-05-04 21:48:37', '2025-04-05 21:48:37',
       '2025-08-28 21:48:37', '2025-10-18 21:48:37',
       '2026-02-02 21:48:37', '2025-05-29 21:48:37',
       '2025-05-27 21:48:37', '2025-09-20 21:48:37',
       '2025-06-05 21:48:37', '2025-11-06 21:48:37',
       '2025-04-28 21:48:37', '2025-04-12 21:48:37',
       '2026-02-11 21:48:37', '2025-08-23 21:48:37',
       '2025-04-30 21:48:37', '2025-04-23 21:48:37',
       '2025-07-02 21:48:37', '2025-07-20 21:48:37',
       '2025-05-22 21:48:37', '2025-07-17 21:48:37',
       '2025-09-25 21:48:37', '2025-04-18 21:48:37',
       '2025-06-28 21:48:37', '2025-06-04 21:48:37',
       '2025-10-03 21:48:37', '2025-07-14 21:48:37',
       '2025-08-06 21:48:37', '2025-10-23 21:48:37',
       '2025-08-29 21:48:37', '2025-04-10 21:48:37',
       '2025-11-30 21:48:37', '2025-06-15 21:48:37',
       '2025-05-08 21:48:37', '2025-11-03 21:48:37',
       '2025-10-30 21:48:37', '2025-11-27 21:48:37',
       '2026-01-11 21:48:37', '2025-07-16 21:48:37',
       '2025-10-09 21:48:37', '2025-12-27 21:48:37',
       '2025-10-12 21:48:37', '2026-01-19 21:48:37',
       '2025-04-04 21:48:37', '2025-07-09 21:48:37',
       '2026-01-06 21:48:37', '2025-09-21 21:48:37',
       '2026-01-01 21:48:37', '2025-09-18 21:48:37',
       '2025-11-25 21:48:37', '2026-02-27 21:48:37',
       '2025-09-02 21:48:37', '2025-12-07 21:48:37',
       '2025-09-06 21:48:37', '2025-11-05 21:48:37',
       '2025-06-30 21:48:37', '2025-07-06 21:48:37',
       '2025-03-15 21:48:37', '2025-08-11 21:48:37',
       '2025-12-23 21:48:37', '2025-09-19 21:48:37',
       '2026-02-24 21:48:37', '2026-02-06 21:48:37',
       '2025-12-13 21:48:37', '2025-09-28 21:48:37',
       '2025-12-12 21:48:37', '2026-01-08 21:48:37',
       '2025-12-20 21:48:37', '2025-09-14 21:48:37',
       '2025-06-26 21:48:37', '2025-07-23 21:48:37',
       '2025-09-29 21:48:37', '2025-10-17 21:48:37',
       '2025-03-30 21:48:37', '2025-05-28 21:48:37',
       '2025-11-17 21:48:37', '2025-05-06 21:48:37',
       '2025-04-13 21:48:37', '2025-08-27 21:48:37',
       '2026-02-28 21:48:37', '2026-01-10 21:48:37',
       '2026-03-06 21:48:37', '2025-12-05 21:48:37',
       '2025-08-17 21:48:37', '2025-11-10 21:48:37',
       '2025-09-24 21:48:37', '2025-08-31 21:48:37',
       '2025-10-26 21:48:37', '2025-08-09 21:48:37',
       '2025-05-19 21:48:37', '2025-07-27 21:48:37',
       '2025-05-18 21:48:37', '2025-06-18 21:48:37',
       '2026-02-13 21:48:37', '2025-09-05 21:48:37',
       '2025-09-03 21:48:37', '2025-05-23 21:48:37',
       '2025-07-30 21:48:37', '2025-05-13 21:48:37',
       '2025-12-04 21:48:37', '2025-11-28 21:48:37',
       '2025-03-22 21:48:37', '2025-09-10 21:48:37',
       '2026-02-04 21:48:37', '2026-03-03 21:48:37',
       '2026-03-02 21:48:37', '2025-06-06 21:48:37',
       '2025-10-02 21:48:37', '2025-12-21 21:48:37',
       '2026-02-23 21:48:37', '2025-11-22 21:48:37',
       '2026-02-26 21:48:37', '2025-06-03 21:48:37',
       '2025-08-26 21:48:37', '2025-11-09 21:48:37',
       '2025-11-02 21:48:37', '2025-12-24 21:48:37',
       '2025-04-14 21:48:37', '2025-05-30 21:48:37',
       '2025-04-16 21:48:37', '2025-10-25 21:48:37',
       '2025-07-28 21:48:37', '2025-10-15 21:48:37',
       '2025-06-08 21:48:37', '2025-11-14 21:48:37',
       '2025-09-23 21:48:37', '2025-04-21 21:48:37',
       '2025-11-29 21:48:37', '2025-09-22 21:48:37',
       '2025-10-07 21:48:37', '2025-08-21 21:48:37',
       '2025-05-17 21:48:37', '2026-02-14 21:48:37',
       '2025-05-09 21:48:37', '2025-11-21 21:48:37',
       '2025-12-15 21:48:37', '2025-07-25 21:48:37',
       '2025-06-27 21:48:37', '2025-10-22 21:48:37',
       '2025-03-21 21:48:37', '2025-04-25 21:48:37',
       '2025-11-07 21:48:37', '2025-03-13 21:48:37',
       '2025-04-19 21:48:37', '2025-08-15 21:48:37',
       '2026-02-18 21:48:37', '2025-07-19 21:48:37',
       '2025-07-11 21:48:37', '2025-04-27 21:48:37',
       '2025-08-24 21:48:37', '2025-09-12 21:48:37',
       '2025-06-24 21:48:37', '2025-03-25 21:48:37',
       '2025-07-05 21:48:37', '2025-06-11 21:48:37',
       '2026-01-26 21:48:37', '2025-03-11 21:48:37',
       '2025-08-04 21:48:37', '2026-01-04 21:48:37',
       '2026-01-18 21:48:37', '2025-09-16 21:48:37',
       '2025-12-30 21:48:37', '2025-04-07 21:48:37',
       '2025-05-12 21:48:37', '2025-07-03 21:48:37',
       '2026-01-17 21:48:37', '2026-01-21 21:48:37',
       '2025-08-08 21:48:37', '2026-01-16 21:48:37',
       '2025-05-10 21:48:37', '2026-01-25 21:48:37',
       '2025-05-01 21:48:37', '2025-06-19 21:48:37',
       '2025-06-21 21:48:37', '2025-04-29 21:48:37',
       '2026-02-17 21:48:37', '2026-02-16 21:48:37',
       '2025-03-18 21:48:37', '2025-10-16 21:48:37',
       '2026-01-14 21:48:37', '2025-10-06 21:48:37',
       '2026-01-09 21:48:37', '2025-04-06 21:48:37',
       '2026-01-31 21:48:37', '2025-11-20 21:48:37',
       '2025-03-16 21:48:37', '2026-01-20 21:48:37',
       '2025-11-04 21:48:37', '2025-04-26 21:48:37',
       '2025-11-16 21:48:37', '2025-12-06 21:48:37',
       '2025-08-14 21:48:37', '2025-06-23 21:48:37',
       '2025-09-30 21:48:37', '2025-12-08 21:48:37',
       '2026-02-01 21:48:37', '2025-11-23 21:48:37',
       '2025-09-17 21:48:37', '2025-09-26 21:48:37',
       '2025-08-05 21:48:37', '2025-05-02 21:48:37',
       '2025-05-14 21:48:37', '2025-10-04 21:48:37',
       '2025-10-01 21:48:37', '2025-10-31 21:48:37',
       '2025-08-12 21:48:37', '2026-01-30 21:48:37',
       '2026-01-15 21:48:37', '2025-12-18 21:48:37',
       '2025-12-29 21:48:37', '2026-01-23 21:48:37',
       '2025-08-10 21:48:37', '2025-07-29 21:48:37',
       '2025-12-10 21:48:37', '2025-07-07 21:48:37',
       '2025-06-01 21:48:37', '2026-02-15 21:48:37',
       '2025-03-28 21:48:37', '2026-02-19 21:48:37',
       '2025-12-19 21:48:37', '2025-12-11 21:48:37',
       '2025-07-21 21:48:37', '2025-03-14 21:48:37',
       '2025-12-09 21:48:37', '2025-12-28 21:48:37',
       '2025-03-23 21:48:37', '2025-10-29 21:48:37',
       '2025-12-01 21:48:37', '2025-05-03 21:48:37',
       '2025-11-15 21:48:37', '2026-03-05 21:48:37',
       '2025-09-04 21:48:37', '2025-08-01 21:48:37',
       '2026-01-24 21:48:37', '2026-03-10 21:48:37',
       '2025-06-13 21:48:37', '2025-07-24 21:48:37',
       '2025-04-17 21:48:37', '2026-01-03 21:48:37',
       '2025-12-22 21:48:37', '2025-11-24 21:48:37',
       '2025-08-30 21:48:37', '2025-09-13 21:48:37',
       '2025-07-04 21:48:37', '2025-09-01 21:48:37',
       '2025-05-20 21:48:37', '2025-05-26 21:48:37',
       '2025-06-14 21:48:37', '2025-05-05 21:48:37',
       '2026-03-08 21:48:37'], dtype=object)

In [19]:
# 4.看房人数的平均值，最大值，最小值
house_df.view_num.min()
house_df.view_num.mean()
house_df.view_num.max()

house_df['view_num'].min()
house_df['view_num'].mean()
house_df['view_num'].max()

house_df['view_num']  # Series对象，如果调用describe()函数报错，可以转换为DataFrame对象
house_df['view_num'].describe()
house_df[['view_num']] # DataFrame对象   describe()函数是DataFrame的函数
house_df[['view_num']].describe()

          view_num
count  2760.000000
mean   2515.567029
std    1454.313282
min      10.000000
25%    1270.250000
50%    2549.000000
75%    3764.000000
max    4999.000000

In [22]:
# 5.查看不同看房人数的房源数量，as_index=False 分组字段不作为行索引(默认为True)
# 6.查看房租价格的分布，例如:平均值，标准差，中位数...
# 7.找到看房人数最多的朝向
# 8.查找最受欢迎的房型
# 9.查找房子的平均租房价格 (元/平米)
# 10，找到出租房源最多的小区